apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  labels:
    app: react-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: port-wallet
  selector:
    app: react-frontend